"""Added relationship between users and restaurants

Revision ID: 8584931d8569
Revises: 2145945551a9
Create Date: 2018-09-12 12:46:45.271768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8584931d8569'
down_revision = '2145945551a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_restaurants',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('restaurants_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['restaurants_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'restaurants_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_restaurants')
    # ### end Alembic commands ###
