"""Added coordinates for users

Revision ID: c212b63d859c
Revises: 8584931d8569
Create Date: 2018-09-12 13:08:10.579824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c212b63d859c'
down_revision = '8584931d8569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('latitude', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('longitude', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'longitude')
    op.drop_column('user', 'latitude')
    # ### end Alembic commands ###
